package: boundary
generate:
  std-http: true
  models: true
import-mapping:
  ./packageA/spec.yaml: github.com/deepmap/oapi-codegen/internal/test/externalref/packageA
  ./packageB/spec.yaml: github.com/deepmap/oapi-codegen/internal/test/externalref/packageB
output: rest_gen.go
# output-options:
#   skip-prune: true
