// Code generated by "stringer -type=CharacterType -output charactertype_gen.go"; DO NOT EDIT.

package session

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PC-0]
	_ = x[NPC-1]
}

const _CharacterType_name = "PCNPC"

var _CharacterType_index = [...]uint8{0, 2, 5}

func (i CharacterType) String() string {
	if i < 0 || i >= CharacterType(len(_CharacterType_index)-1) {
		return "CharacterType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CharacterType_name[_CharacterType_index[i]:_CharacterType_index[i+1]]
}
