@startuml "Entities"

skinparam linetype ortho

class Table {
    +id: String
    +title: String
}

class User {
    +id: String
}

class Player {
    +name: String
    +fatePoints: Integer
}

class Aspect {
    +id: String
    +name: String
}

Table -u-> User: gameMaster
Table "1" *-d-> "*" Aspect: aspects
Table "1" *-r-> "*" Player: players
Player -u-> User: user
Player "1" *-d-> "*" Aspect: aspects

@enduml