name: CI

on:
  push:

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm i
        working-directory: app

      - name: Build assembly
        run: npm run build
        working-directory: app

  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.18.0-beta2"

      - name: Create dummy frontend
        run: touch internal/boundary/public
        working-directory: backend

      - name: Run tests
        run: go test ./... -cover
        working-directory: backend
